package org.repositoryminer.metrics.codesmell;

public enum CodeSmellId {

	BRAIN_CLASS, BRAIN_METHOD, COMPLEX_METHOD, GOD_CLASS, LONG_METHOD, REFUSED_PARENT_BEQUEST, DATA_CLASS, DEPTH_OF_INHERITANCE_TREE, FEATURE_ENVY;

}